#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ================================================== #
# This file is a part of PYGPT package               #
# Website: https://pygpt.net                         #
# GitHub:  https://github.com/szczyglis-dev/py-gpt   #
# MIT License                                        #
# Created By  : Marcin Szczygliński                  #
# Updated Date: 2026.09.22 00:20:00                  #
# ================================================== #

import math
from dataclasses import dataclass, field
from typing import Any, Callable, List, Optional, Sequence

from llama_index.core.base.llms.generic_utils import messages_to_history_str
from llama_index.core.indices.prompt_helper import PromptHelper
from llama_index.core.prompts import PromptTemplate
from llama_index.core.schema import MetadataMode, QueryBundle


@dataclass
class PreparedRAGContext:
    """Prepared retrieval result ready to append to the model prompt."""

    query: str
    retrieval_query: str
    context: str = ""
    nodes: List[Any] = field(default_factory=list)
    packed_chunks: List[str] = field(default_factory=list)
    condensed: bool = False

    @property
    def has_context(self) -> bool:
        return bool(self.context.strip())


class RAGContextPreparer:
    """Prepare LlamaIndex retrieval output for a direct provider chat call.

    The class deliberately stops before LlamaIndex response synthesis.  It keeps
    the useful pre-answer part of the chat-engine pipeline (optional standalone
    question generation, retrieval, post-processing and token-aware packing),
    while the final answer is generated by PyGPT's normal LLM chat path.  This
    avoids relying on the chat-engine streaming response synthesizer.
    """

    DEFAULT_TOP_K = 5

    # Retrieval scores are not portable as an absolute confidence scale, so
    # relevance filtering is relative to the best result in the current query.
    # These values are intentionally conservative: they remove clear outliers
    # while keeping clusters of similarly ranked results.
    RELATIVE_SCORE_FLOOR = 0.45
    ADJACENT_SCORE_RATIO = 0.55
    ADJACENT_DROP_MAX_BEST_RATIO = 0.75

    # Match the behavior of LlamaIndex's CondensePlusContextChatEngine without
    # depending on its private _run_c3/_condense_question methods.
    CONDENSE_PROMPT = PromptTemplate(
        "Given the following conversation between a user and an AI assistant and a follow up question from user,\n"
        "rephrase the follow up question to be a standalone question.\n\n"
        "Chat History:\n\n"
        "{chat_history}\n\n"
        "Follow Up Input: {question}\n\n"
        "Standalone question:"
    )

    CONDENSE_MODES = {
        "best",
        "condense_question",
        "condense_plus_context",
    }

    CONTEXT_PREFIX = (
        "# Retrieved context (RAG)\n\n"
        "<rag_context>\n"
    )
    CONTEXT_SUFFIX = "\n</rag_context>"

    # Used only to estimate how much room is left for retrieved material in the
    # *final* direct chat call.  The real request remains structured ChatMessages.
    PACK_TEMPLATE = PromptTemplate(
        "{request_overhead}\n\n"
        "# Retrieved context (RAG)\n\n"
        "<rag_context>\n"
        "{context_str}\n"
        "</rag_context>"
    )

    def __init__(
            self,
            top_k: int = DEFAULT_TOP_K,
            node_postprocessors: Optional[Sequence[Any]] = None,
            logger: Optional[Callable[[str], None]] = None,
    ):
        self.top_k = top_k
        self.node_postprocessors = list(node_postprocessors or [])
        self.logger = logger

    def prepare(
            self,
            index,
            llm,
            query: str,
            history: Optional[List[Any]] = None,
            chat_mode: str = "context",
            system_prompt: str = "",
            tools: Optional[List[Any]] = None,
            context_window_limit: Optional[int] = None,
    ) -> PreparedRAGContext:
        """Return retrieval context prepared for a single final LLM call.

        ``simple`` intentionally returns no RAG context.  ``context`` retrieves
        with the original user request.  Modes that normally condense a follow-up
        question first use the same standalone-question idea before retrieval.
        """
        result = PreparedRAGContext(
            query=query,
            retrieval_query=query,
        )
        if index is None or chat_mode == "simple":
            return result

        history = history or []
        retrieval_query = self._prepare_retrieval_query(
            llm=llm,
            query=query,
            history=history,
            chat_mode=chat_mode,
        )
        result.retrieval_query = retrieval_query
        result.condensed = retrieval_query.strip() != query.strip()

        nodes = self._retrieve_nodes(index, retrieval_query)
        nodes = self._apply_postprocessors(nodes, retrieval_query)
        nodes = self._clean_nodes(nodes)
        nodes = self._filter_by_relative_relevance(nodes)
        result.nodes = nodes
        if not nodes:
            self._log("RAG context: no nodes retrieved")
            return result

        source_chunks = self._format_nodes(nodes)
        packed_chunks = self._pack_context(
            llm=llm,
            chunks=source_chunks,
            query=query,
            history=history,
            system_prompt=system_prompt,
            tools=tools,
            context_window_limit=context_window_limit,
        )
        result.packed_chunks = packed_chunks
        if not packed_chunks:
            return result

        # One final provider call can consume one context-window-sized packed
        # chunk.  repack() keeps retrieval order, so chunk #1 contains the
        # highest-ranked material first when the full retrieval does not fit.
        packed = packed_chunks[0].strip()
        if packed:
            result.context = self.CONTEXT_PREFIX + packed + self.CONTEXT_SUFFIX

        if len(packed_chunks) > 1:
            self._log(
                "RAG context exceeded one final-call context budget; "
                f"using the first packed chunk out of {len(packed_chunks)}"
            )
        self._log(
            f"RAG context prepared: nodes={len(nodes)}, "
            f"packed_chunks={len(packed_chunks)}, condensed={result.condensed}"
        )
        return result

    def _prepare_retrieval_query(
            self,
            llm,
            query: str,
            history: List[Any],
            chat_mode: str,
    ) -> str:
        """Generate a standalone retrieval query for condense chat modes."""
        if chat_mode not in self.CONDENSE_MODES or not history:
            return query

        try:
            history_str = messages_to_history_str(history)
            prompt = self.CONDENSE_PROMPT.format(
                chat_history=history_str,
                question=query,
            )
            # CondensePlusContextChatEngine uses llm.complete() for this step.
            response = llm.complete(prompt)
            condensed = str(response).strip()
            if condensed:
                self._log(f"RAG retrieval query condensed: {condensed}")
                return condensed
        except Exception as e:
            # Retrieval must remain available even if a provider cannot perform
            # the optional condense call.  This mirrors a safe degradation to
            # ContextChatEngine-style retrieval with the original question.
            self._log(f"RAG query condense failed, using original query: {e}")
        return query

    def _retrieve_nodes(self, index, query: str) -> List[Any]:
        kwargs = {}
        if self.top_k is not None and self.top_k > 0:
            kwargs["similarity_top_k"] = self.top_k
        retriever = index.as_retriever(**kwargs)
        return list(retriever.retrieve(query) or [])

    def _apply_postprocessors(self, nodes: List[Any], query: str) -> List[Any]:
        if not nodes or not self.node_postprocessors:
            return nodes
        query_bundle = QueryBundle(query)
        processed = nodes
        for postprocessor in self.node_postprocessors:
            processed = postprocessor.postprocess_nodes(
                processed,
                query_bundle=query_bundle,
            )
        return list(processed or [])

    def _clean_nodes(self, nodes: List[Any]) -> List[Any]:
        """Drop empty/duplicate nodes while preserving retriever ranking."""
        output = []
        seen = set()
        for node in nodes:
            text = self._get_node_content(node, with_metadata=False)
            if not text:
                continue

            wrapped = getattr(node, "node", None)
            node_id = (
                getattr(node, "node_id", None)
                or getattr(node, "id_", None)
                or getattr(wrapped, "node_id", None)
                or getattr(wrapped, "id_", None)
            )
            key = ("id", str(node_id)) if node_id is not None else ("text", text)
            if key in seen:
                continue
            seen.add(key)
            output.append(node)
        return output

    def _filter_by_relative_relevance(self, nodes: List[Any]) -> List[Any]:
        """Drop clearly weaker retrieval results using per-query score shape.

        Absolute similarity values vary between embedding models and vector
        stores, so this deliberately avoids a global cutoff such as ``0.2`` or
        ``0.5``.  Filtering is enabled only when all nodes expose finite,
        positive scores in the same descending order returned by the retriever.
        Otherwise the retriever ranking is preserved unchanged.

        The best node is always kept.  Lower-ranked nodes are removed when they
        fall far enough below the best result, or when there is a pronounced
        local score cliff.  Once such a cliff is reached, all weaker nodes are
        discarded because the retriever has already ordered them best-to-worst.
        """
        if len(nodes) < 2:
            return nodes

        scores = [self._get_node_score(node) for node in nodes]
        if any(score is None for score in scores):
            self._log("RAG relevance filter skipped: one or more nodes have no score")
            return nodes

        try:
            numeric = [float(score) for score in scores]
        except (TypeError, ValueError):
            self._log("RAG relevance filter skipped: non-numeric score")
            return nodes

        if not all(math.isfinite(score) for score in numeric):
            self._log("RAG relevance filter skipped: non-finite score")
            return nodes

        # Relative ratios are meaningful for the usual positive similarity
        # scores.  For distance-like/negative scales we leave ranking untouched
        # rather than guessing at backend-specific semantics.
        if numeric[0] <= 0 or any(score < 0 for score in numeric):
            self._log(
                "RAG relevance filter skipped: score scale is not positive similarity"
            )
            return nodes

        # LlamaIndex retrievers are expected to return best-first.  If a custom
        # backend violates that ordering, do not make relevance assumptions.
        if any(numeric[i] > numeric[i - 1] for i in range(1, len(numeric))):
            self._log("RAG relevance filter skipped: scores are not descending")
            return nodes

        self._log(
            "RAG relevance scores: "
            + ", ".join(f"#{i + 1}={score:.6g}" for i, score in enumerate(numeric))
        )

        best = numeric[0]
        keep_count = len(nodes)
        drop_reason = None

        for i in range(1, len(numeric)):
            current = numeric[i]
            previous = numeric[i - 1]
            relative_to_best = current / best
            relative_to_previous = current / previous if previous > 0 else 1.0

            if relative_to_best < self.RELATIVE_SCORE_FLOOR:
                keep_count = i
                drop_reason = (
                    f"score={current:.6g}, best_ratio={relative_to_best:.3f} "
                    f"< {self.RELATIVE_SCORE_FLOOR:.2f}"
                )
                break

            if (
                    relative_to_previous < self.ADJACENT_SCORE_RATIO
                    and relative_to_best < self.ADJACENT_DROP_MAX_BEST_RATIO
            ):
                keep_count = i
                drop_reason = (
                    f"score={current:.6g}, previous_ratio={relative_to_previous:.3f} "
                    f"< {self.ADJACENT_SCORE_RATIO:.2f}"
                )
                break

        kept = nodes[:keep_count]
        if keep_count < len(nodes):
            self._log(
                f"RAG relevance filter: kept {keep_count}/{len(nodes)} nodes; "
                f"first dropped rank={keep_count + 1} ({drop_reason})"
            )
        else:
            self._log(
                f"RAG relevance filter: kept all {len(nodes)} nodes; "
                f"best={best:.6g}, worst={numeric[-1]:.6g}"
            )
        return kept

    @staticmethod
    def _get_node_score(node: Any) -> Optional[float]:
        if node is None:
            return None
        try:
            return node.get_score()
        except (AttributeError, TypeError, ValueError):
            return getattr(node, "score", None)

    def _format_nodes(self, nodes: List[Any]) -> List[str]:
        """Create explicit ranked source blocks using LLM-visible metadata."""
        chunks = []
        for i, node in enumerate(nodes, start=1):
            text = self._get_node_content(node, with_metadata=True)
            if not text:
                continue
            chunks.append(f"[Source {i}]\n{text.strip()}")
        return chunks

    def _pack_context(
            self,
            llm,
            chunks: List[str],
            query: str,
            history: List[Any],
            system_prompt: str,
            tools: Optional[List[Any]] = None,
            context_window_limit: Optional[int] = None,
    ) -> List[str]:
        """Token-aware repack of retrieved chunks for one direct chat request."""
        if not chunks:
            return []

        try:
            history_str = messages_to_history_str(history) if history else ""
            request_overhead = self._build_request_overhead(
                system_prompt=system_prompt,
                history=history_str,
                query=query,
            )
            prompt = self.PACK_TEMPLATE.partial_format(
                request_overhead=request_overhead,
            )
            helper = PromptHelper.from_llm_metadata(
                llm.metadata,
                chunk_overlap_ratio=0.0,
            )
            if context_window_limit is not None and context_window_limit > 0:
                helper = PromptHelper(
                    context_window=min(helper.context_window, context_window_limit),
                    num_output=helper.num_output,
                    chunk_overlap_ratio=0.0,
                )
            return helper.repack(
                prompt,
                chunks,
                llm=llm,
                tools=tools,
                padding=16,
            )
        except ValueError as e:
            # PromptHelper raises when the fixed request (system + history +
            # output reserve) already leaves no positive room for RAG.  Do not
            # force extra context into an overfull request.
            self._log(f"RAG context skipped: no token budget left after packing: {e}")
            return []
        except Exception as e:
            # Custom/provider wrappers can expose incomplete metadata. Preserve
            # retrieval in that exceptional case rather than failing the request.
            self._log(f"RAG context token-aware packing failed, using raw context: {e}")
            return ["\n\n".join(chunks)]

    @staticmethod
    def _build_request_overhead(
            system_prompt: str,
            history: str,
            query: str,
    ) -> str:
        parts = []
        if system_prompt:
            parts.append("System instructions:\n" + system_prompt)
        if history:
            parts.append("Conversation history:\n" + history)
        parts.append("Current user request:\n" + query)
        return "\n\n".join(parts)

    @staticmethod
    def _get_node_content(node: Any, with_metadata: bool = True) -> str:
        """Return node text using LlamaIndex's LLM metadata policy when possible."""
        if node is None:
            return ""

        wrapped = getattr(node, "node", None) or node
        if hasattr(wrapped, "get_content"):
            try:
                mode = MetadataMode.LLM if with_metadata else MetadataMode.NONE
                value = wrapped.get_content(metadata_mode=mode)
                if value is not None:
                    return str(value).strip()
            except (AttributeError, TypeError, ValueError):
                pass

        text = getattr(node, "text", None)
        if text is None:
            text = getattr(wrapped, "text", None)
        return str(text).strip() if text is not None else ""

    def _log(self, message: str):
        if self.logger is not None:
            try:
                self.logger(message)
            except Exception:
                pass
