#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ================================================== #
# This file is a part of PYGPT package               #
# Website: https://pygpt.net                         #
# GitHub:  https://github.com/szczyglis-dev/py-gpt   #
# MIT License                                        #
# Created By  : Marcin Szczygliński                  #
# Updated Date: 2026.09.29 14:42:00                  #
# ================================================== #

def setup() -> dict:
    return {
        "settings": {
            "api_key": {
                "type": "str", "default": "", "secret": True,
                "urls": {"API Keys": "https://console.x.ai"},
            },
            "api_base": {"type": "str", "default": "https://api.x.ai/v1"},
            "extra": {
                "management_api_key": {
                    "type": "str", "default": "", "secret": True,
                    "label": "settings.api_key_management.xai",
                    "desc": "settings.api_key_management.xai.desc",
                    "use_locale": True,
                    "urls": {"API Keys": "https://console.x.ai"},
                },
                "native": {
                    "type": "bool", "default": True,
                    "label": "settings.api_native_xai",
                    "desc": "settings.api_native_xai.desc",
                    "use_locale": True,
                },
            },
        },
        "remote_tools": {
            "web_search": {
                "unsupported_prefixes": ['grok-3'],
                "unsupported_models": [],
                "type": "bool",
                "label": "settings.remote_tools.xai.web_search",
                "default": True,
                "desc": "settings.remote_tools.xai.web_search.desc",
                "use_locale": True,
                "legacy_key": "remote_tools.xai.web_search",
                "tool": True,
            },
            "x_search": {
                "type": "bool",
                "label": "settings.remote_tools.xai.x_search",
                "default": False,
                "desc": "settings.remote_tools.xai.x_search.desc",
                "use_locale": True,
                "legacy_key": "remote_tools.xai.x_search",
                "tool": True,
            },
            "code_execution": {
                "type": "bool",
                "label": "settings.remote_tools.xai.code_execution",
                "default": False,
                "desc": "settings.remote_tools.xai.code_execution.desc",
                "use_locale": True,
                "legacy_key": "remote_tools.xai.code_execution",
                "tool": True,
            },
            "mcp": {
                "type": "bool",
                "label": "settings.remote_tools.xai.mcp",
                "default": False,
                "desc": "settings.remote_tools.xai.mcp.desc",
                "use_locale": True,
                "legacy_key": "remote_tools.xai.mcp",
                "tool": True,
            },
            "mcp.args": {
                "type": "textarea",
                "label": "settings.remote_tools.xai.mcp.args",
                "urls": {
                    "xAI Docs": "https://docs.x.ai/docs/guides/tools/remote-mcp-tools",
                },
                "default": "{\n    \"server_url\": \"https://mcp.deepwiki.com/mcp\n}",
                "desc": "settings.remote_tools.xai.mcp.args.desc",
                "use_locale": True,
                "legacy_key": "remote_tools.xai.mcp.args",
            },
            "collections": {
                "type": "bool",
                "label": "settings.remote_tools.xai.collections",
                "default": False,
                "desc": "settings.remote_tools.xai.collections.desc",
                "use_locale": True,
                "legacy_key": "remote_tools.xai.collections",
                "tool": True,
            },
            "collections.args": {
                "type": "text",
                "label": "settings.remote_tools.xai.collections.args",
                "urls": {
                    "xAI Docs": "https://docs.x.ai/docs/guides/tools/collections-search-tool",
                },
                "default": "",
                "desc": "settings.remote_tools.xai.collections.args.desc",
                "use_locale": True,
                "legacy_key": "remote_tools.xai.collections.args",
            },
            "return_citations": {
                "type": "bool",
                "default": True,
                "label": "Return citations",
                "desc": "Optional provider tool parameter: return_citations",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.return_citations",
            },
            "max_results": {
                "type": "int",
                "default": 0,
                "label": "Max results",
                "desc": "Optional provider tool parameter: max_results",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.max_results",
                "min": 0,
            },
            "inline_citations": {
                "type": "bool",
                "default": True,
                "label": "Inline citations",
                "desc": "Optional provider tool parameter: inline_citations",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.inline_citations",
            },
            "include_code_output": {
                "type": "bool",
                "default": True,
                "label": "Include code output",
                "desc": "Optional provider tool parameter: include_code_output",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.include_code_output",
            },
            "use_encrypted_content": {
                "type": "bool",
                "default": False,
                "label": "Use encrypted content",
                "desc": "Optional provider tool parameter: use_encrypted_content",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.use_encrypted_content",
            },
            "max_turns": {
                "type": "int",
                "default": 0,
                "label": "Max turns",
                "desc": "Optional provider tool parameter: max_turns",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.max_turns",
                "min": 0,
            },
            "x.included_handles": {
                "type": "text",
                "default": "",
                "label": "X / included handles",
                "desc": "Optional provider tool parameter: x.included_handles",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.x.included_handles",
            },
            "x.excluded_handles": {
                "type": "text",
                "default": "",
                "label": "X / excluded handles",
                "desc": "Optional provider tool parameter: x.excluded_handles",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.x.excluded_handles",
            },
            "x.min_favs": {
                "type": "int",
                "default": 0,
                "label": "X / min favs",
                "desc": "Optional provider tool parameter: x.min_favs",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.x.min_favs",
                "min": 0,
            },
            "x.min_views": {
                "type": "int",
                "default": 0,
                "label": "X / min views",
                "desc": "Optional provider tool parameter: x.min_views",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.x.min_views",
                "min": 0,
            },
            "from_date": {
                "type": "text",
                "default": "",
                "label": "From date",
                "desc": "Optional provider tool parameter: from_date",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.from_date",
            },
            "to_date": {
                "type": "text",
                "default": "",
                "label": "To date",
                "desc": "Optional provider tool parameter: to_date",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.to_date",
            },
            "web.country": {
                "type": "text",
                "default": "",
                "label": "Web / country",
                "desc": "Optional provider tool parameter: web.country",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.web.country",
            },
            "web.safe_search": {
                "type": "combo",
                "default": "",
                "label": "Web / safe search",
                "desc": "Optional provider tool parameter: web.safe_search",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.web.safe_search",
                "choices": [{'': 'Default'}, {'true': 'Enabled'}, {'false': 'Disabled'}],
                "value_type": "optional_bool",
            },
            "web.enable_image_understanding": {
                "type": "bool",
                "default": False,
                "label": "Web / enable image understanding",
                "desc": "Optional provider tool parameter: web.enable_image_understanding",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.web.enable_image_understanding",
            },
            "x.enable_image_understanding": {
                "type": "bool",
                "default": False,
                "label": "X / enable image understanding",
                "desc": "Optional provider tool parameter: x.enable_image_understanding",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.x.enable_image_understanding",
            },
            "x.enable_video_understanding": {
                "type": "bool",
                "default": False,
                "label": "X / enable video understanding",
                "desc": "Optional provider tool parameter: x.enable_video_understanding",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.x.enable_video_understanding",
            },
            "web.allowed_websites": {
                "type": "text",
                "default": "",
                "label": "Web / allowed websites",
                "desc": "Optional provider tool parameter: web.allowed_websites",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.web.allowed_websites",
            },
            "web.excluded_websites": {
                "type": "text",
                "default": "",
                "label": "Web / excluded websites",
                "desc": "Optional provider tool parameter: web.excluded_websites",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.web.excluded_websites",
            },
            "web.enable_image_search": {
                "type": "bool",
                "default": False,
                "label": "Web / enable image search",
                "desc": "Optional provider tool parameter: web.enable_image_search",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.web.enable_image_search",
            },
            "store_messages": {
                "type": "combo",
                "default": "",
                "label": "Store messages",
                "desc": "Optional provider tool parameter: store_messages",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.xai.store_messages",
                "choices": [{'': 'Default'}, {'true': 'Enabled'}, {'false': 'Disabled'}],
                "value_type": "optional_bool",
            },
            "mode": {
                "type": "text",
                "default": "auto",
                "hidden": True,
                "legacy_key": "remote_tools.xai.mode",
            },
            "sources.news": {
                "type": "text",
                "default": False,
                "hidden": True,
                "legacy_key": "remote_tools.xai.sources.news",
            },
            "sources.web": {
                "type": "text",
                "default": True,
                "hidden": True,
                "legacy_key": "remote_tools.xai.sources.web",
            },
            "sources.x": {
                "type": "text",
                "default": True,
                "hidden": True,
                "legacy_key": "remote_tools.xai.sources.x",
            },
        },
    }
