#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ================================================== #
# This file is a part of PYGPT package               #
# Website: https://pygpt.net                         #
# GitHub:  https://github.com/szczyglis-dev/py-gpt   #
# MIT License                                        #
# Created By  : Marcin Szczygliński                  #
# Updated Date: 2026.09.29 14:42:00                  #
# ================================================== #

def setup() -> dict:
    return {
        "settings": {
            "api_key": {
                "type": "str", "default": "", "secret": True,
                "urls": {"API Keys": "https://platform.claude.com/settings/keys"},
            },
            "api_base": {"type": "str", "default": "https://api.anthropic.com/v1"},
            "extra": {
                "native": {
                    "type": "bool", "default": True,
                    "label": "settings.api_native_anthropic",
                    "desc": "settings.api_native_anthropic.desc",
                    "use_locale": True,
                },
            },
        },
        "remote_tools": {
            "web_search": {
                "unsupported_prefixes": ['claude-3-5'],
                "unsupported_models": [],
                "type": "bool",
                "label": "settings.remote_tools.anthropic.web_search",
                "default": True,
                "desc": "settings.remote_tools.anthropic.web_search.desc",
                "use_locale": True,
                "legacy_key": "remote_tools.anthropic.web_search",
                "tool": True,
            },
            "web_fetch": {
                "type": "bool",
                "label": "settings.remote_tools.anthropic.web_fetch",
                "default": False,
                "desc": "settings.remote_tools.anthropic.web_fetch.desc",
                "use_locale": True,
                "legacy_key": "remote_tools.anthropic.web_fetch",
                "tool": True,
            },
            "code_execution": {
                "type": "bool",
                "label": "settings.remote_tools.anthropic.code_execution",
                "default": False,
                "desc": "settings.remote_tools.anthropic.code_execution.desc",
                "use_locale": True,
                "legacy_key": "remote_tools.anthropic.code_execution",
                "tool": True,
            },
            "mcp": {
                "type": "bool",
                "label": "settings.remote_tools.anthropic.mcp",
                "default": False,
                "desc": "settings.remote_tools.anthropic.mcp.desc",
                "use_locale": True,
                "legacy_key": "remote_tools.anthropic.mcp",
                "tool": True,
            },
            "mcp.tools": {
                "type": "textarea",
                "label": "settings.remote_tools.anthropic.mcp.tools",
                "urls": {
                    "Anthropic Docs": "https://platform.claude.com/docs/en/agents-and-tools/remote-mcp-servers",
                },
                "default": "[\n   {\n        \"type\": \"mcp_toolset\",\n        \"mcp_server_name\": \"example-mcp\"\n   }\n]",
                "desc": "settings.remote_tools.anthropic.mcp.tools.desc",
                "use_locale": True,
                "legacy_key": "remote_tools.anthropic.mcp.tools",
            },
            "mcp.mcp_servers": {
                "type": "textarea",
                "label": "settings.remote_tools.anthropic.mcp.mcp_servers",
                "urls": {
                    "Anthropic Docs": "https://platform.claude.com/docs/en/agents-and-tools/remote-mcp-servers",
                },
                "default": "[\n   {\n        \"type\": \"url\",\n        \"url\": \"https://mcp.example.com/sse\",\n        \"name\": \"example-mcp\",\n        \"authorization_token\": \"YOUR_TOKEN\"\n   }\n]",
                "desc": "settings.remote_tools.anthropic.mcp.mcp_servers.desc",
                "use_locale": True,
                "legacy_key": "remote_tools.anthropic.mcp.mcp_servers",
            },
            "computer_use": {
                "type": "bool",
                "label": "settings.remote_tools.anthropic.computer_use",
                "urls": {
                    "Anthropic Docs": "https://platform.claude.com/docs/en/agents-and-tools/tool-use/computer-use-tool",
                },
                "default": False,
                "desc": "settings.remote_tools.anthropic.computer_use.desc",
                "use_locale": True,
                "legacy_key": "remote_tools.anthropic.computer_use",
                "tool": True,
            },
            "web_search.type": {
                "type": "text",
                "default": "web_search_20250305",
                "label": "Web search / type",
                "desc": "Optional provider tool parameter: web_search.type",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.anthropic.web_search.type",
            },
            "web_search.max_uses": {
                "type": "int",
                "default": 0,
                "label": "Web search / max uses",
                "desc": "Optional provider tool parameter: web_search.max_uses",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.anthropic.web_search.max_uses",
                "min": 0,
            },
            "web_search.allowed_domains": {
                "type": "text",
                "default": "",
                "label": "Web search / allowed domains",
                "desc": "Optional provider tool parameter: web_search.allowed_domains",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.anthropic.web_search.allowed_domains",
            },
            "web_search.blocked_domains": {
                "type": "text",
                "default": "",
                "label": "Web search / blocked domains",
                "desc": "Optional provider tool parameter: web_search.blocked_domains",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.anthropic.web_search.blocked_domains",
            },
            "web_search.user_location.city": {
                "type": "text",
                "default": "",
                "label": "Web search / user location / city",
                "desc": "Optional provider tool parameter: web_search.user_location.city",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.anthropic.web_search.user_location.city",
            },
            "web_search.user_location.region": {
                "type": "text",
                "default": "",
                "label": "Web search / user location / region",
                "desc": "Optional provider tool parameter: web_search.user_location.region",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.anthropic.web_search.user_location.region",
            },
            "web_search.user_location.country": {
                "type": "text",
                "default": "",
                "label": "Web search / user location / country",
                "desc": "Optional provider tool parameter: web_search.user_location.country",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.anthropic.web_search.user_location.country",
            },
            "web_search.user_location.timezone": {
                "type": "text",
                "default": "",
                "label": "Web search / user location / timezone",
                "desc": "Optional provider tool parameter: web_search.user_location.timezone",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.anthropic.web_search.user_location.timezone",
            },
            "web_fetch.max_uses": {
                "type": "int",
                "default": 0,
                "label": "Web fetch / max uses",
                "desc": "Optional provider tool parameter: web_fetch.max_uses",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.anthropic.web_fetch.max_uses",
                "min": 0,
            },
            "web_fetch.allowed_domains": {
                "type": "text",
                "default": "",
                "label": "Web fetch / allowed domains",
                "desc": "Optional provider tool parameter: web_fetch.allowed_domains",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.anthropic.web_fetch.allowed_domains",
            },
            "web_fetch.blocked_domains": {
                "type": "text",
                "default": "",
                "label": "Web fetch / blocked domains",
                "desc": "Optional provider tool parameter: web_fetch.blocked_domains",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.anthropic.web_fetch.blocked_domains",
            },
            "web_fetch.citations.enabled": {
                "type": "bool",
                "default": True,
                "label": "Web fetch / citations / enabled",
                "desc": "Optional provider tool parameter: web_fetch.citations.enabled",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.anthropic.web_fetch.citations.enabled",
            },
            "web_fetch.max_content_tokens": {
                "type": "int",
                "default": 0,
                "label": "Web fetch / max content tokens",
                "desc": "Optional provider tool parameter: web_fetch.max_content_tokens",
                "advanced": True,
                "use_locale": False,
                "legacy_key": "remote_tools.anthropic.web_fetch.max_content_tokens",
                "min": 0,
            },
        },
    }
