"""Application-wide computer-control indicator, independent of chat rendering."""
from PySide6.QtCore import Qt, QTimer, Signal, Slot
from PySide6.QtWidgets import QLabel, QApplication

from pygpt_net.utils import trans
from .computer_use_frame import ComputerUseFrame


class ComputerUseBadge(QLabel):
    active_changed = Signal(bool)
    stop_requested = Signal()
    escape_requested = Signal()

    def __init__(self, window):
        super().__init__(window.menuBar())
        self.window = window
        self._desktop_badge = None
        self._active = False
        self._keyboard_listener = None
        self.setObjectName('computerUseBadge')
        self.setAttribute(Qt.WA_TransparentForMouseEvents)
        self.desktop_frame = ComputerUseFrame(self)
        self._hide_timer = QTimer(self)
        self._hide_timer.setSingleShot(True)
        self._hide_timer.setInterval(800)
        self._hide_timer.timeout.connect(self._retire)
        self.active_changed.connect(self.set_active)
        self.stop_requested.connect(self.stop)
        self.escape_requested.connect(self._interrupt)
        self.hide()
        app = QApplication.instance()
        app.aboutToQuit.connect(self.stop)
        app.primaryScreenChanged.connect(self.reposition)

    @Slot(bool)
    def set_active(self, active):
        # Every dispatch path (native providers, plugins and agent workers) shares
        # this guard. Queued activation after ESC must never resurrect the frame.
        if self.window.core.config.get('computer_use.sandbox', False) or (
                active and self.window.controller.kernel.stopped()):
            self.stop()
            return
        if not active:
            # Renderer cleanup/idle events also occur between tool continuations.
            # A following computer action cancels this pending retirement.
            if not self._hide_timer.isActive():
                self._hide_timer.start()
            return
        self._hide_timer.stop()
        self._active = True
        if active:
            self.setText(trans('tool.status.computer_use'))
            light = self.window.controller.theme.common.is_light_theme_id(
                self.window.core.config.get('theme', 'dark'))
            color = '#248544' if light else '#55ff70'
            background = '#e5f5e9' if light else '#17351e'
            self.setStyleSheet(
                f'QLabel#computerUseBadge {{ color: {color}; background: {background}; '
                'font-weight: bold; border-radius: 6px; padding: 8px 14px; margin: 0px; }')
            self.adjustSize()
            if self._desktop_badge is None:
                self._desktop_badge = QLabel(None, Qt.Tool | Qt.FramelessWindowHint |
                    Qt.WindowStaysOnTopHint | Qt.WindowTransparentForInput | Qt.WindowDoesNotAcceptFocus)
                self._desktop_badge.setObjectName('computerUseBadge')
                self._desktop_badge.setAttribute(Qt.WA_ShowWithoutActivating)
                self._desktop_badge.setAttribute(Qt.WA_TransparentForMouseEvents)
                self._desktop_badge.setFocusPolicy(Qt.NoFocus)
            self._desktop_badge.setText(self.text())
            self._desktop_badge.setStyleSheet(self.styleSheet())
            self._desktop_badge.adjustSize()
            self.reposition()
            self._desktop_badge.show()
        self.desktop_frame.show()
        self._start_escape_listener()

    @Slot()
    def stop(self):
        self._hide_timer.stop()
        self._retire()

    def _retire(self):
        self._active = False
        if self._keyboard_listener is not None:
            self._keyboard_listener.stop()
            self._keyboard_listener = None
        self.hide()
        if self._desktop_badge is not None:
            self._desktop_badge.hide()
        self.desktop_frame.hide()

    def reposition(self, *_):
        if self._desktop_badge is None:
            return
        screen = QApplication.primaryScreen()
        if screen is None:
            return
        rect = screen.geometry()
        self._desktop_badge.move(rect.x() + (rect.width() - self._desktop_badge.width()) // 2, rect.y() + 50)
        self._desktop_badge.raise_()

    def _start_escape_listener(self):
        if self._keyboard_listener is not None:
            return
        try:
            from pynput.keyboard import Key, Listener
            def on_press(key, injected=False):
                # ESC generated by the computer tool itself is not a user stop.
                if self._active and key == Key.esc and not injected:
                    self.escape_requested.emit()
            listener = Listener(on_press=on_press)
            listener.start()
            self._keyboard_listener = listener
        except Exception as error:
            self.window.core.debug.log(error)

    @Slot()
    def _interrupt(self):
        if not self._active:
            return
        self.stop()
        self.window.controller.access.on_escape(close_dialog=False)
