"""Runnable TTS provider example that generates a short WAV tone."""

import math
import struct
import wave

from pygpt_net.provider.audio_output.base import BaseProvider


class ExampleAudioOutput(BaseProvider):
    def __init__(self):
        super().__init__()
        self.id = "example_audio_output"
        self.name = "Example tone output"

    def init_options(self):
        self.plugin.add_option(
            "example_tone_hz",
            type="int",
            value=440,
            min=100,
            max=2000,
            label="Tone frequency (Hz)",
            description="Frequency generated by the tutorial audio-output provider.",
            tab=self.id,
        )

    def speech(self, text):
        # A real TTS provider would synthesize `text`. This tutorial generates
        # a playable tone whose duration changes with the text length.
        path = self.prepare_output_path("wav")
        sample_rate = 16000
        frequency = int(self.plugin.get_option_value("example_tone_hz") or 440)
        duration = min(1.5, max(0.20, len(str(text)) / 80.0))
        amplitude = 10000
        frames = int(sample_rate * duration)

        with wave.open(path, "wb") as wav:
            wav.setnchannels(1)
            wav.setsampwidth(2)
            wav.setframerate(sample_rate)
            for i in range(frames):
                value = int(amplitude * math.sin(2.0 * math.pi * frequency * i / sample_rate))
                wav.writeframesraw(struct.pack("<h", value))
        return path

    def is_configured(self):
        return True
